export const GET_DOCTORS_REQUEST = "GET_DOCTORS_REQUEST";
export const GET_DOCTORS_SUCCESS = "GET_DOCTORS_SUCCESS";
export const GET_DOCTORS_FAILURE = "GET_DOCTORS_FAILURE";

export const REFRESH_MESSAGE = "REFRESH_MESSAGE";
export const REFRESH_ERROR = "REFRESH_ERROR";