export const GET_DOCTORS_REQUEST = "GET_DOCTORS_REQUEST";
export const GET_DOCTORS_SUCCESS = "GET_DOCTORS_SUCCESS";
export const GET_DOCTORS_FAILURE = "GET_DOCTORS_FAILURE";

export const GET_DOCTOR_BY_ID_REQUEST = "GET_DOCTOR_BY_ID_REQUEST";
export const GET_DOCTOR_BY_ID_SUCCESS = "GET_DOCTOR_BY_ID_SUCCESS";
export const GET_DOCTOR_BY_ID_FAILURE = "GET_DOCTOR_BY_ID_FAILURE";

export const GET_DOCTOR_BY_SPECIALITY_REQUEST = "GET_DOCTOR_BY_SPECIALITY_REQUEST";
export const GET_DOCTOR_BY_SPECIALITY_SUCCESS = "GET_DOCTOR_BY_SPECIALITY_SUCCESS";
export const GET_DOCTOR_BY_SPECIALITY_FAILURE = "GET_DOCTOR_BY_SPECIALITY_FAILURE";

export const REFRESH_MESSAGE = "REFRESH_MESSAGE";
export const REFRESH_ERROR = "REFRESH_ERROR";