export const ADD_SPECIALITY_REQUEST = "ADD_SPECIALITY_REQUEST";
export const ADD_SPECIALITY_SUCCESS = "ADD_SPECIALITY_SUCCESS";
export const ADD_SPECIALITY_FAILURE = "ADD_SPECIALITY_FAILURE";

export const REFRESH_MESSAGE = "REFRESH_MESSAGE";
export const REFRESH_ERROR = "REFRESH_ERROR";