export const GET_SPECIALITY_REQUEST = "GET_SPECIALITY_REQUEST";
export const GET_SPECIALITY_SUCCESS = "GET_SPECIALITY_SUCCESS";
export const GET_SPECIALITY_FAILURE = "GET_SPECIALITY_FAILURE";

export const REFRESH_MESSAGE = "REFRESH_MESSAGE";
export const REFRESH_ERROR = "REFRESH_ERROR";