export const ADD_DOCTOR_REQUEST = "ADD_DOCTOR_REQUEST";
export const ADD_DOCTOR_SUCCESS = "ADD_DOCTOR_SUCCESS";
export const ADD_DOCTOR_FAILURE = "ADD_DOCTOR_FAILURE";

export const REFRESH_MESSAGE = "REFRESH_MESSAGE";
export const REFRESH_ERROR = "REFRESH_ERROR";